//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekSquidAgentSim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string FormalName { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public float Satisfaction { get; set; }
        public float Happiness { get; set; }
        public int TraitOne { get; set; }
        public int TraitTwo { get; set; }
        public string Membership { get; set; }
    }
}
