//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekSquidAgentSim
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suspect
    {
        public int ID { get; set; }
        public string Owner { get; set; }
        public string Brand { get; set; }
        public string Type { get; set; }
        public int AgeInMonths { get; set; }
        public float PurchasePrice { get; set; }
    }
}
